const routes = {
  home: "/",
  dashboard: "/dashboard",
  users: "/users",
  guarantors: "/guarantors",
  decision_models: "/decision_models",
  savings: "/savings",
  loan_requests: "/loan_requests",
  whitelist: "/whitelist",
  karma: "/karma",
  orgainization: "/orgainization",
  savings_products: "/savings_products",
  fees_and_charges: "/fees_and_charges",
  transactions: "/transactions",
  services: "/services",
  settlements: "/settlements",
  reports: "/reports",
  preferences: "/preferences",
  fees_and_pricing: "/fees_and_pricing",
  audit_logs: "/audit_logs",
  systems_messages: "/systems_messages",
  logout: "/",
  loans: "/loans",
  loan_products: "/loan_products",
  service_account: "/service_account",
  user_details: "/users/:userId",
};

export default routes;
