const routes = {
  home: "/",
  dashboard: "/dashboard",
  users: "/dashboard/users",
  guarantors: "/dashboard/guarantors",
  decision_models: "/dashboard/decision_models",
  savings: "/dashboard/savings",
  loan_requests: "/dashboard/loan_requests",
  whitelist: "/dashboard/whitelist",
  karma: "/dashboard/karma",
  orgainization: "/dashboard/orgainization",
  savings_products: "/dashboard/savings_products",
  fees_and_charges: "/dashboard/fees_and_charges",
  transactions: "/dashboard/transactions",
  services: "/dashboard/users",
  settlements: "/dashboard/settlements",
  reports: "/dashboard/reports",
  preferences: "/dashboard/preferences",
  fees_and_pricing: "/dashboard/fees_and_pricing",
  audit_logs: "/dashboard/audit_logs",
  systems_messages: "/dashboard/systems_messages",
  logout: "/",
  loans: "/dashboard/loans",
  loan_products: "/dashboard/loan_products",
  service_account: "/dashboard/service_account",
};

export default routes;
